---
- hosts: localhost
  connection: local
  roles:
    - utils
    - zsh
    - role: linux
      when: ansible_facts['system'] == 'Linux'
    - role: windows
      when: ansible_facts['system'] == 'Linux' and is_wsl
