- name: Zshrc and Bashrc
  hosts: localhost
  gather_facts: no
  vars:
    homebrew_prefix: "/home/linuxbrew/.linuxbrew"
  tasks:
    - name: "Configure shell profiles"
      ansible.builtin.blockinfile:
        path: "~/{{ item }}"
        block: |
          # Homebrew shell variables
          eval "$({{ homebrew_prefix }}/bin/brew shellenv)"

          # Preview file content using 'bat'
          FZF_CTRL_T_OPTS="
            --preview 'bat --style=numbers --color=always --line-range :500 {}'
            --bind 'ctrl-/:change-preview-window(down|hidden|)'"

          # Preview directory tree for ALT-C
          FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

          # Starship prompt
          eval "$(starship init zsh)"
      loop:
        - .bashrc
        - .zshrc

    - name: "Starship prompt config"
      ansible.builtin.shell: |
        starship preset catppuccin-powerline -o ~/.config/starship.toml
      args:
        creates: "~/.config/starship.toml"
