---
galaxy_info:
  author: devenv-playbook
  role_name: utils
  description: Install Homebrew and development tools
  license: MIT
  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: macOS
      versions:
        - all
  min_ansible_version: "2.15"
dependencies: []
