---
- name: "locale: Set to en_US.UTF-8"
  ansible.builtin.shell: |
    locale-gen en_US.UTF-8
    update-locale LANG=en_US.UTF-8
  become: true
  args:
    creates: "/etc/locale.conf"
  when: ansible_facts.os_family == "Debian"
