# fzf is a general-purpose command-line fuzzy finder written in Go.
# It is a fast, efficient, and easy-to-use tool that can be used to find
# files, directories, and other items in a fuzzy manner.
---
- name: "fzf: Install package"
  community.general.homebrew:
    name:
      - fzf
    state: present

- name: "fzf: Install keybindings and fuzzy completion"
  ansible.builtin.shell: |
    {{ homebrew_prefix }}/opt/fzf/install --all
  args:
    creates: ~/.fzf.zsh

- ansible.builtin.include_role:
    name: zsh
    tasks_from: mkdir_zshrc_d_prefix.yml

- name: "fzf: Create zsh.d config"
  ansible.builtin.copy:
    dest: "{{ zshrc_d_prefix }}/fzf.zsh"
    mode: "0644"
    content: |
      # Preview file content using 'bat'
      export FZF_CTRL_T_OPTS="
        --preview 'bat --style=numbers --color=always --line-range :500 {}'
        --bind 'ctrl-/:change-preview-window(down|hidden|)'"

      # Preview directory tree for ALT-C
      export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
