---
- name: "zsh: Install zsh"
  ansible.builtin.package:
    name:
      - zsh
    state: present
  become: true

- name: "zsh: Set default shell"
  ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    shell: /bin/zsh
  become: true

- name: "zsh: Load {{ zshrc_d_prefix }}/*.zsh"
  ansible.builtin.blockinfile:
    path: "~/.zshrc"
    block: |
      # Load {{ zshrc_d_prefix }}/*.zsh
      for ZSH_FILE in {{ zshrc_d_prefix }}/*.zsh(N); do
        source "${ZSH_FILE}"
      done

      # WSL: Change to Linux home directory
      cd ~

- name: "zsh: Setup Oh-My-Zsh"
  ansible.builtin.include_tasks: oh-my-zsh.yml

- name: "zsh: Setup fzf"
  ansible.builtin.import_tasks: fzf.yml

- name: "zsh: Setup eza"
  ansible.builtin.import_tasks: eza.yml

- name: "zsh: Setup Starship"
  ansible.builtin.include_tasks: starship.yml
