---
- name: "Oh-My-Zsh: Install from Github"
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: "~/.oh-my-zsh"
    update: "{{ update_plugins | default(false) | bool }}"

- name: "Oh-My-Zsh: Install plugins"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.name }}"
    update: "{{ update_plugins | default(false) | bool }}"
  loop: "{{ zsh_oh_my_zsh_plugins }}"

- name: "Oh-My-Zsh: Create .zshrc from template"
  ansible.builtin.copy:
    src: "~/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "~/.zshrc"
    remote_src: true
    force: false
    mode: "0644"

- name: "Oh-My-Zsh: Update plugins config"
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=\(git'
    line:
      "plugins=(git {{ zsh_oh_my_zsh_plugins | map(attribute='name') | join(' ')
      }})"
    state: present

- name: "Oh-My-Zsh: Disable theme for Starship"
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: "^ZSH_THEME="
    line: "ZSH_THEME="
    state: present
