---
- name: "starship: Install"
  community.general.homebrew:
    name:
      - starship
    state: present

- name: "starship: Configure"
  ansible.builtin.shell: |
    "{{ homebrew_prefix }}"/opt/starship/bin/starship preset catppuccin-powerline -o ~/.config/starship.toml
  args:
    creates: "~/.config/starship.toml"

- ansible.builtin.include_role:
    name: zsh
    tasks_from: mkdir_zshrc_d_prefix.yml

- name: "starship: Add zsh.d config"
  ansible.builtin.copy:
    dest: "{{ zshrc_d_prefix }}/starship.zsh"
    mode: "0644"
    content: |
      eval "$(starship init zsh)"
