---
- name: "Starship: Install package"
  community.general.homebrew:
    name:
      - starship
    state: present

- name: "Starship: Configure catppuccin-powerline"
  ansible.builtin.shell: |
    "{{ homebrew_prefix }}"/opt/starship/bin/starship preset catppuccin-powerline -o ~/.config/starship.toml
  args:
    creates: "~/.config/starship.toml"

- name: "Starship: Enable line_break so prompt character is on a new line"
  community.general.ini_file:
    path: "~/.config/starship.toml"
    section: line_break
    option: disabled
    value: "false"
    no_extra_spaces: false
    mode: "0644"

- name: "Starship: Add zsh.d config"
  ansible.builtin.copy:
    dest: "{{ zshrc_d_prefix }}/starship.zsh"
    mode: "0644"
    content: |
      eval "$(starship init zsh)"
