---
- name: "utils/homebrew: Install dependencies"
  ansible.builtin.package:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
      - tar
    state: present
  become: true

- name: "utils/homebrew: Create prefix directory"
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0755"
  become: true

- name: "utils/homebrew: Install Homebrew"
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://github.com/Homebrew/brew/tarball/main | tar xz --strip 1 -C {{ homebrew_prefix }}
    eval "$({{ homebrew_prefix }}/bin/brew shellenv)"
    brew update --force --quiet
    chmod -R go-w {{ homebrew_prefix }}/share/zsh
  args:
    creates: "{{ homebrew_prefix }}/bin/brew"
    executable: /bin/bash

- ansible.builtin.include_role:
    name: zsh
    tasks_from: mkdir_zshrc_d_prefix.yml

- name: "utils/homebrew: Create zsh config"
  ansible.builtin.copy:
    dest: "{{ zshrc_d_prefix }}/homebrew.zsh"
    mode: "0644"
    content: |
      eval "$({{ homebrew_prefix }}/bin/brew shellenv)"

- name: "utils/homebrew: Add taps"
  community.general.homebrew_tap:
    name: oven-sh/bun
    state: present

- name: "utils/homebrew: Install packages"
  community.general.homebrew:
    name:
      # System utils
      - btop
      - htop
      - ripgrep
      - fd
      - bat
      - glow
      - gdu # gdu-go
      - neofetch
      # devtools - General
      - prettier
      # devtools - Javascript/Typescript
      - oven-sh/bun/bun
      - npm
      - pnpm
      # devtools - Python
      - uv
    state: present
