---
- name: "homebrew: Check if brew is installed"
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: utils_homebrew_bin

- name: "homebrew: Install dependencies"
  ansible.builtin.package:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
      - tar
    state: present
  become: true
  when: not utils_homebrew_bin.stat.exists

- name: "homebrew: Create prefix directory"
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0755"
  become: true
  when: not utils_homebrew_bin.stat.exists

- name: "homebrew: Install package"
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://github.com/Homebrew/brew/tarball/main | tar xz --strip 1 -C {{ homebrew_prefix }}
    eval "$({{ homebrew_prefix }}/bin/brew shellenv)"
    brew update --force --quiet
    chmod -R go-w {{ homebrew_prefix }}/share/zsh
  args:
    creates: "{{ homebrew_prefix }}/bin/brew"
    executable: /bin/bash
  when: not utils_homebrew_bin.stat.exists

- ansible.builtin.include_role:
    name: zsh
    tasks_from: mkdir_zshrc_d_prefix.yml

- name: "homebrew: Create zsh.d config"
  ansible.builtin.copy:
    dest: "{{ zshrc_d_prefix }}/homebrew.zsh"
    mode: "0644"
    content: |
      eval "$({{ homebrew_prefix }}/bin/brew shellenv)"

- name: "homebrew: Tap oven-sh/bun"
  community.general.homebrew_tap:
    name: oven-sh/bun
    state: present

- name: "homebrew: Install system utils"
  community.general.homebrew:
    name:
      - btop
      - htop
      - ripgrep
      - fd
      - bat
      - glow
      - gdu # gdu-go
      - fastfetch
    state: present

- name: "homebrew: Install devtools"
  community.general.homebrew:
    name:
      - prettier
      - oven-sh/bun/bun
      - npm
      - pnpm
      - uv
    state: present
