---
- ansible.builtin.include_tasks:
    file: homebrew.yml
    apply:
      tags: homebrew
  tags: homebrew
- ansible.builtin.include_tasks:
    file: abtop.yml
    apply:
      tags: abtop
  tags: abtop
- ansible.builtin.include_tasks:
    file: tmux.yml
    apply:
      tags: tmux
  tags: tmux
- ansible.builtin.include_tasks:
    file: git.yml
    apply:
      tags: git
  tags: git
- ansible.builtin.include_tasks:
    file: neovim.yml
    apply:
      tags: neovim
  tags: neovim
- ansible.builtin.include_tasks:
    file: opencode.yml
    apply:
      tags: opencode
  tags: opencode
- ansible.builtin.include_tasks:
    file: claude-code.yml
    apply:
      tags: claude-code
  tags: claude-code
- ansible.builtin.include_tasks:
    file: claude-usage-tracker.yml
    apply:
      tags: claude-usage-tracker
  tags: claude-usage-tracker
- ansible.builtin.include_tasks:
    file: cmux.yml
    apply:
      tags: cmux
  tags: cmux
