---
- ansible.builtin.include_tasks: homebrew.yml
- ansible.builtin.include_tasks: tmux.yml
- ansible.builtin.include_tasks: git.yml
- ansible.builtin.include_tasks: neovim.yml
- ansible.builtin.include_tasks: opencode.yml
- ansible.builtin.include_tasks: claude-code.yml
- ansible.builtin.include_tasks: claude-usage-tracker.yml
- ansible.builtin.include_tasks: cmux.yml
