---
- name: "Utils: Configure Homebrew"
  ansible.builtin.include_tasks: homebrew.yml

- name: "Utils: Configure tmux"
  ansible.builtin.include_tasks: tmux.yml

- name: "Utils: Configure git"
  ansible.builtin.include_tasks: git.yml

- name: "Utils: Configure neovim"
  ansible.builtin.include_tasks: neovim.yml

- name: "Utils: Configure opencode"
  ansible.builtin.include_tasks: opencode.yml
