---
- name: "opencode: Tap opencode"
  community.general.homebrew_tap:
    name: anomalyco/tap
    state: present

- name: "opencode: Install package"
  community.general.homebrew:
    name: opencode
    state: present

- name: "opencode: Create config directory"
  ansible.builtin.file:
    path: "~/.local/share/opencode"
    state: directory
    mode: "0755"

- name: "opencode: Copy auth.json if provided"
  ansible.builtin.copy:
    src: "~/.local/share/opencode/auth.json"
    dest: "~/.local/share/opencode/auth.json"
    mode: "0600"
    remote_src: true
  failed_when: false
