---
- name: "Homebrew: Install dependencies"
  ansible.builtin.package:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
      - tar
    state: present
  become: true

- name: "Homebrew: Create prefix directory"
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0755"
  become: true

- name: "Homebrew: Install Homebrew"
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://github.com/Homebrew/brew/tarball/main | tar xz --strip 1 -C {{ homebrew_prefix }}
    eval "$({{ homebrew_prefix }}/bin/brew shellenv)"
    brew update --force --quiet
    chmod -R go-w {{ homebrew_prefix }}/share/zsh
  args:
    creates: "{{ homebrew_prefix }}/bin/brew"

- name: "Homebrew: Add taps"
  community.general.homebrew_tap:
    name: oven-sh/bun
    state: present

- name: "Homebrew: Install packages"
  community.general.homebrew:
    name:
      # System utils
      - btop
      - htop
      - ripgrep
      - fd
      - bat
      - eza
      - neovim
      - fzf
      - glow
      - gdu # gdu-go
      - starship
      - neofetch
      # devtools - General
      - prettier
      # devtools - Javascript/Typescript
      - oven-sh/bun/bun
      - npm
      - pnpm
      # devtools - Python
      - uv
    state: present

- name: "Homebrew: Configure fzf"
  ansible.builtin.shell: |
    $(brew --prefix)/opt/fzf/install --all
  args:
    creates: ~/.fzf.zsh

- name: "Homebrew: Configure eza"
  ansible.builtin.import_tasks: eza.yml
